routes/frontend.php
<?php
use App\Http\Controllers\FrontendController;


Route::get('/', [FrontendController::class, 'home']);
Route::get('/change-web-language/{lang}', [FrontendController::class, 'changeLanguage']);
Route::group(['prefix' => 'user'], function () {
    Route::get('/register', [FrontendController::class, 'register']);
    Route::post('/register', [FrontendController::class, 'userRegister']);
    Route::get('/login', [FrontendController::class, 'login']);
    Route::post('/login', [FrontendController::class, 'userLogin']);
    Route::get('/resetPassword', [FrontendController::class, 'resetPassword']);
    Route::post('/resetPassword', [FrontendController::class, 'userResetPassword']);
    Route::get('/org-register', [FrontendController::class, 'orgRegister']);
    Route::post('/org-register', [FrontendController::class, 'organizerRegister']);
});

    Route::get('/all-events', [FrontendController::class, 'allEvents']);
    Route::post('/all-events', [FrontendController::class, 'allEvents']);
    Route::get('/events-category/{id}/{name}', [FrontendController::class, 'categoryEvents']);
    Route::get('/event-type/{type}', [FrontendController::class, 'eventType']);
    Route::get('/event/{id}/{name}', [FrontendController::class, 'eventDetail']);
    Route::get('/organization/{id}/{name}', [FrontendController::class, 'orgDetail']);
    Route::post('/report-event', [FrontendController::class, 'reportEvent']);
    Route::get('/all-category', [FrontendController::class, 'allCategory']);
    Route::get('/all-blogs', [FrontendController::class, 'blogs']);
    Route::get('/blog-detail/{id}/{name}', [FrontendController::class, 'blogDetail']);
    Route::get('/contact', [FrontendController::class, 'contact']);

    Route::group(['middleware' =>'appuser'], function () {
        Route::get('/checkout/{id}', [FrontendController::class, 'checkout']);
        Route::post('/createOrder', [FrontendController::class, 'createOrder']);
        Route::get('/user/profile', [FrontendController::class, 'profile']);
        Route::get('/add-favorite/{id}/{type}', [FrontendController::class, 'addFavorite']);
        Route::get('/add-followList/{id}', [FrontendController::class, 'addFollow']);
        Route::post('/add-bio', [FrontendController::class, 'addBio']);
        Route::get('/change-password', [FrontendController::class, 'changePassword']);
        Route::post('/change-password', [FrontendController::class, 'changeUserPassword']);
        Route::post('/upload-profile-image', [FrontendController::class, 'uploadProfileImage']);
        Route::get('/my-tickets', [FrontendController::class, 'userTickets']);
        Route::get('/update_profile', [FrontendController::class, 'update_profile']);
        Route::post('/update_user_profile', [FrontendController::class, 'update_user_profile']);
        Route::get('/getOrder/{id}', [FrontendController::class, 'getOrder']);
        Route::post('/add-review', [FrontendController::class, 'addReview']);
        Route::get('/web/create-payment/{id}', [FrontendController::class, 'makePayment']);
        Route::post('/web/payment/{id}', [FrontendController::class, 'initialize'])->name('frontendPay');
        Route::get('/web/rave/callback/{id}', [FrontendController::class, 'callback'])->name('frontendCallback');

    });

    Route::get('/tnc', [FrontendController::class, 'tnc']);
    Route::get('/privacy-policy', [FrontendController::class, 'privacyPolicy']);
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\AppUserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\NotificationTemplateController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\TaxController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\LicenseController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\SmsEventsController;
use App\Http\Controllers\BoatsController;
use App\Http\Controllers\ApiController;
use App\Http\Controllers\StripeWebhookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::post('/admin/login', [LicenseController::class, 'adminLogin']);
Route::post('/saveEnvData', [LicenseController::class, 'saveEnvData']);
Route::post('/saveAdminData', [LicenseController::class, 'saveAdminData']);
// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin/home', [UserController::class, 'adminDashboard']);
    Route::get('/organization/home', [UserController::class, 'organizationDashboard']);    
    Route::get('/{id}/{name}/tickets', [TicketController::class, 'index']);
    Route::delete('/deleteTickets/{id}', [TicketController::class, 'deleteTickets']);
    Route::get('/{id}/ticket/create', [TicketController::class, 'create']);
    Route::post('/ticket/create', [TicketController::class, 'store']);
    Route::get('/ticket/edit/{id}', [TicketController::class, 'edit']);
    Route::post('/ticket/update/{id}', [TicketController::class, 'update']);
    
    Route::get('/block-user/{id}', [AppUserController::class, 'blockUser']);
    Route::get('/block-scanner/{id}', [UserController::class, 'blockScanner']);
    Route::get('/admin-setting', [SettingController::class, 'index']);
    Route::get('/license-setting', [LicenseController::class, 'licenseSetting']);
    Route::post('/save-license-setting', [LicenseController::class, 'saveLicenseSetting']);    
    Route::post('/save-general-setting', [SettingController::class, 'store']);
    Route::post('/save-mail-setting', [SettingController::class, 'saveMailSetting']);
    Route::post('/save-verification-setting', [SettingController::class, 'saveVerificationSetting']);    
    Route::post('/save-organization-setting', [SettingController::class, 'saveOrganizationSetting']);        
    Route::post('/save-pushNotification-setting', [SettingController::class, 'saveOnesignalSetting']);    
    Route::post('/save-sms-setting', [SettingController::class, 'saveSmsSetting']);    
    Route::post('/additional-setting', [SettingController::class, 'additionalSetting']);    
    Route::post('/support-setting', [SettingController::class, 'supportSetting']);    
    Route::post('/save-payment-setting', [SettingController::class, 'savePaymentSetting']);    
    Route::get('/profile', [UserController::class, 'viewProfile']);    
    Route::post('/edit-profile', [UserController::class, 'editProfile']);    
    Route::post('/change-password', [UserController::class, 'changePassword']);        
    Route::get('/orders', [OrderController::class, 'index']);    
    Route::get('/orders/{id}', [OrderController::class, 'show']);    
    Route::get('/order-invoice/{id}', [OrderController::class, 'orderInvoice']);    
    Route::get('/user-review', [OrderController::class, 'userReview']);    
    Route::get('/change-review-status/{id}', [OrderController::class, 'changeReviewStatus']);    
    Route::get('/delete-review/{id}', [OrderController::class, 'deleteReview']);        
    Route::post('/get-month-event', [EventController::class, 'getMonthEvent']);        
    Route::get('/event-gallery/{id}', [EventController::class, 'eventGallery']);        
    Route::post('/add-event-gallery', [EventController::class, 'addEventGallery']);        
    Route::get('/remove-image/{image}/{id}', [EventController::class, 'removeEventImage']);  

    Route::get('/scanner', [UserController::class, 'scanner']);
    Route::get('/scanner/create', [UserController::class, 'scannerCreate']);    
    Route::post('/scanner', [UserController::class, 'addScanner']);
    Route::get('/getScanner/{id}', [UserController::class, 'getScanner']);
    Route::get('/organization-report/customer', [OrderController::class, 'customerReport']);
    Route::post('/organization-report/customer', [OrderController::class, 'customerReport']);
    Route::get('/organization-report/orders', [OrderController::class, 'ordersReport']);
    Route::post('/organization-report/orders', [OrderController::class, 'ordersReport']);
    Route::get('/organization-report/revenue', [OrderController::class, 'orgRevenueReport']);
    Route::post('/organization-report/revenue', [OrderController::class, 'orgRevenueReport']);
    
    Route::get('/admin-report/customer', [OrderController::class, 'adminCustomerReport']);
    Route::post('/admin-report/customer', [OrderController::class, 'adminCustomerReport']);
    Route::get('/admin-report/organization', [OrderController::class, 'adminOrgReport']);
    Route::post('/admin-report/organization', [OrderController::class, 'adminOrgReport']);
    Route::get('/admin-report/revenue', [OrderController::class, 'adminRevenueReport']);
    Route::post('/admin-report/revenue', [OrderController::class, 'adminRevenueReport']);
    
    Route::get('/change-language/{lang}', [UserController::class, 'changeLanguage']);
    Route::get('/getStatistics/{month}', [OrderController::class, 'getStatistics']);
    Route::get('/admin-report/settlement', [OrderController::class, 'settlementReport']);    
    Route::get('/view-user/{id}', [AppUserController::class, 'userDetail']);
    Route::post('/pay-to-org', [OrderController::class, 'payToUser']);
    Route::post('/pay-to-organization', [OrderController::class, 'payToOrganization']);
    Route::get('/view-settlement/{id}', [OrderController::class, 'viewSettlement']);
   
    Route::get('get-code/{code}', [OrderController::class, 'getQrCode']);
    Route::get('/language/download_sample_file',[LanguageController::class,'download_sample_file']);

    Route::resources([
        'roles' => RoleController::class, 
        'tax' => TaxController::class, 
        'faq' => FaqController::class, 
        'banner' => BannerController::class, 
        'app-user' => AppUserController::class, 
        'users' =>  UserController::class, 
        'blog' =>  BlogController::class, 
        'feedback' =>  FeedbackController::class, 
        'coupon' =>  CouponController::class,   
        'category' =>  CategoryController::class, 
        'location' =>  LocationController::class, 
        'events' =>  EventController::class,    
        'notification-template' =>  NotificationTemplateController::class,
        'language' => LanguageController::class,
    ]);

    Route::get('/admin/sms-events', [SmsEventsController::class, 'index']);
    Route::get('tax-forms', [TaxController::class, 'viewTaxForms']);
    Route::get('/admin/boat-settings', [BoatsController::class, 'boatSettings'])->name('boat-settings');
    Route::get('/admin/boat-settings/create-maina', [BoatsController::class, 'createMaina']);
    Route::get('/admin/boat-settings/create-items', [BoatsController::class, 'createItems']);
    Route::get('/admin/boat-settings/create-models', [BoatsController::class, 'createModels']);
    Route::get('/admin/boat-settings/edit-maina/{id}', [BoatsController::class, 'editMaina'])->name('admin.boat-settings.edit-maina');
    Route::get('/admin/boat-settings/edit-items/{id}', [BoatsController::class, 'editItems'])->name('admin.boat-settings.edit-items');
    Route::get('/admin/boat-settings/edit-policy/{id}', [BoatsController::class, 'editCancellationPolicy'])->name('admin.boat-settings.edit-policy');
    Route::get('/admin/boat-settings/edit-models/{id}', [BoatsController::class, 'editBoatModels'])->name('admin.boat-settings.edit-models');
    Route::get('/admin/boat-settings/edit-split-payment/{id}', [BoatsController::class, 'editSplitPayment'])->name('admin.boat-settings.edit-split-payment');
    Route::post('/admin/boat-settings/store-maina', [BoatsController::class, 'storeMaina'])->name('admin.boat-settings.store-maina');
    Route::post('/admin/boat-settings/store-items', [BoatsController::class, 'storeItems'])->name('admin.boat-settings.store-items');
    Route::post('/admin/boat-settings/store-models', [BoatsController::class, 'storeModels'])->name('admin.boat-settings.store-models');
    Route::post('/admin/boat-settings/update-maina/{id}', [BoatsController::class, 'updateMaina'])->name('admin.boat-settings.update-maina');
    Route::post('/admin/boat-settings/update-items/{id}', [BoatsController::class, 'updateItems'])->name('admin.boat-settings.update-items');
    Route::post('/admin/boat-settings/update-models/{id}', [BoatsController::class, 'updateModels'])->name('admin.boat-settings.update-models');
    Route::post('/admin/boat-settings/update-policy/{id}', [BoatsController::class, 'updateCancellationPolicy'])->name('admin.boat-settings.update-policy');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'category_id',
        'tags',
        'image',
        'status',
    ];
    protected $appends = ['imagePath'];


    protected $table = 'blog';

    public function category()
    {
        return $this->hasOne('App\Models\Category', 'id', 'category_id');
    }
    public function getImagePathAttribute()
    {
        return url('images/upload') . '/';
    }
}

resources/views/frontend/allCategory.blade.php
@extends('frontend.master', ['activePage' => 'category'])

@section('content')
 
{{-- breadcrumbs --}}
    @include('frontend.layout.breadcrumbs', [
        'title' => __('Featured Category'),            
        'page' => __('Category'),            
    ]) 

{{-- page content --}}
  
<section class="property-grid grid">
    <div class="container">
      <div class="row">
        <div id="" class="category-section">
            <div class="row">
              @foreach ($data as $item)
                <div class="carousel-item-c col-lg-4 col-md-6 col-sm-12">
                  <div class="card-box-b card-shadow news-box box-shadow radius-10">
                    <div class="img-box-b">
                      <img src="{{url('images/upload/'.$item->image)}}" alt="" class="img-b img-fluid">
                    </div>
                    <div class="card-overlay">
                      <div class="card-header-b">                     
                        <div class="card-title-b">
                          <h2 class="title-2">
                            <a href="{{url('events-category/'.$item->id.'/'. preg_replace('/\s+/', '-', $item->name))}}">{{$item->name}}</a>
                          </h2>
                        </div>                     
                      </div>
                    </div>
                  </div>
                </div>
              @endforeach    
            </div>               
          </div>                 
      </div>

    </div>
</section>

@endsection

resources/views/frontend/blog.blade.php
@extends('frontend.master', ['activePage' => 'blog'])

@section('content')
 
{{-- breadcrumbs --}}
    @include('frontend.layout.breadcrumbs', [
        'title' => __('Our Latest blog'),            
        'page' => __('Blogs'),            
    ]) 

{{-- page content --}}
  
<section class="property-grid grid">
    <div class="container">
      <div class="row">
     
        @foreach ($blogs as $item)
            <div class="col-lg-4">
              <div class="owl-theme blog-section mb-5">                
                  <div class="carousel-item-c">
                    
                    <div class="card-box-b card-shadow news-box radius-10">
                      <div class="fav-section">                     
                        @if(Auth::guard('appuser')->check())                                     
                          <button type="button" onclick="addFavorite({{$item->id}},'blog')" class="btn p-0"> <i class="fa fa-heart {{in_array($item->id,array_filter(explode(',',Auth::guard('appuser')->user()->favorite_blog)))==true?'active':''}}"></i></button>
                        @else 
                          <button type="button" class="btn p-0"> <a href="{{url('user/login')}}"><i class="fa fa-heart"></i></a></button>
                        @endif
                      </div>
                      <div class="img-box-b">
                        <img src="{{url('images/upload/'.$item->image)}}" alt="" class="img-b img-fluid">
                      </div>
                      <div class="card-overlay"></div>               
                    </div>
                    <div class="card-header-b">
                      <div class="card-title-b">
                        <h2 class="title-2">
                          <a href="{{url('blog-detail/'.$item->id.'/'.preg_replace('/\s+/', '-', $item->title))}}" title="{{$item->title}}">{{strlen($item->title)>=50? substr($item->title,0,50).'...':$item->title}} </a>
                        </h2>
                      </div>
                      <div class="card-category-b">
                        <span><i class="fa fa-sitemap"></i>{{$item->category->name}}</span>
                        <span class="date-b"><i class="fa fa-calendar"></i>{{$item->created_at->format('d M.Y')}}</span>
                      </div>                     
                    </div>
                  </div> 
                
              </div>
            </div>
        @endforeach              
      </div>

    </div>
</section>

@endsection

resources/views/frontend/home.blade.php
@extends('frontend.master', ['activePage' => 'home'])

@section('content')
     <section class="section-property section-t8 section-b4">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="title-wrap d-flex justify-content-between">
                <div class="title-box">
                  <h2 class="title-a">Featured Events</h2>
                </div>
               
              </div>
            </div>
          </div>
          <div id="" class="event-section owl-theme">
            <div class="row">            
              @foreach ($events as $item)
                @if($loop->iteration <= 6)
                <div class="carousel-item-b col-lg-4 col-md-6 col-sm-6 mb-4">
                  <div class="fav-section">                     
                    @if(Auth::guard('appuser')->check())                                     
                      <button type="button" onclick="addFavorite({{$item->id}},'event')" class="btn p-0"> <i class="fa fa-heart {{in_array($item->id,array_filter(explode(',',Auth::guard('appuser')->user()->favorite)))==true?'active':''}}"></i></button>
                    @else 
                      <button type="button" class="btn p-0"> <a href="{{url('user/login')}}"><i class="fa fa-heart"></i></a></button>
                    @endif
                  </div>
                  <div class="card-box-a card-shadow box-shadow radius-10">
                    <div class="img-box-a">
                      <img src="{{url($item->pictures[0]->image_path)}}" alt="" class="img-a img-fluid">
                    </div>
                    <div class="card-overlay">
                      <div class="card-overlay-a-content">
                        <div class="card-header-a">
                          <h2 class="card-title-a">
                            <a href="{{url('event/'.$item->id.'/'.preg_replace('/\s+/', '-', $item->name))}}">{{ $item->name}}</a>
                          </h2>
                        </div>
                        <div class="card-body-a">
                          <div class="price-box d-flex">
                            <span class="price-a">{{$item->start_time->format('l').', '.$item->start_time->format('d F Y')}}</span>
                          </div>
                          <a href="{{url('event/'.$item->id.'/'.preg_replace('/\s+/', '-', $item->name))}}" class="link-a">{{__('More Detail')}}
                            <span class="ion-ios-arrow-forward"></span>
                          </a>
                        </div>
                        <div class="card-footer-a">
                          <ul class="card-info d-flex justify-content-around">
                            <li>
                              <h4 class="card-info-title">{{__('Type')}}</h4>
                              <span>{{@$item->category->name}}</span>
                            </li>
                           <!--  <li>
                              <h4 class="card-info-title">{{__('People')}}</h4>
                              <span>{{$item->people}}</span>
                            </li>
                            <li>
                              <h4 class="card-info-title">{{__('Sold')}}</h4>
                              <span>{{$item->sold_ticket.' ticket'}} </span>
                            </li> -->
                            <li>
                              <h4 class="card-info-title">{{__('Available')}}</h4>
                              <span>{{$item->available_ticket.' ticket'}}</span>
                            </li>                                                 
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>  
                @endif
              @endforeach  
            </div>         
          </div>
        </div>
      </section>  

    <section class="section-news section-t4 section-b4 bg-gray">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="title-wrap d-flex justify-content-between">
              <div class="title-box">
                <h2 class="title-a">Featured Category</h2>
              </div>            
            </div>
          </div>
        </div>
        <div id="" class="category-section">
          <div class="row">          
              <div class="carousel-item-c col-lg-4 col-md-6 col-sm-6">
                <div class="card-box-b card-shadow-cat news-box radius-10">
                  <div class="img-box-b">
                    <img src="{{url('images/upload/events.jpg')}}" alt="" class="img-b img-fluid">
                  </div>
                  <div class="card-overlay">
                    <div class="card-header-b">                     
                      <div class="card-title-b">
                        <h2 class="title-2">
                          <a href="{{url('all-events')}}" style="color: black !important;">Events </a>
                        </h2>
                      </div>                     
                    </div>
                  </div>
                </div>
              </div>

              <div class="carousel-item-c col-lg-4 col-md-6 col-sm-6">
                <div class="card-box-b card-shadow-cat news-box radius-10">
                  <div class="img-box-b">
                    <img src="{{url('images/upload/boat.jpg')}}" alt="" class="img-b img-fluid">
                  </div>
                  <div class="card-overlay">
                    <div class="card-header-b">                     
                      <div class="card-title-b">
                        <h2 class="title-2">
                          <a href="{{url('all-boats')}}" style="color: black !important;">Boat Booking</a>
                        </h2>
                      </div>                     
                    </div>
                  </div>
                </div>
              </div>


              <div class="carousel-item-c col-lg-4 col-md-6 col-sm-6">
                <div class="card-box-b card-shadow-cat news-box radius-10">
                  <div class="img-box-b">
                    <img src="{{url('images/upload/water.jpg')}}" alt="" class="img-b img-fluid">
                  </div>
                  <div class="card-overlay">
                    <div class="card-header-b">                     
                      <div class="card-title-b">
                        <h2 class="title-2">
                          <a href="{{url('all-sports')}}" style="color: black !important;">Water Sports</a>
                        </h2>
                      </div>                     
                    </div>
                  </div>
                </div>
              </div>
                
          </div>               
        </div>
      </div>
    </section>

  <!--   <section class="section-news section-t4 section-b4 mt-4 bg-gray">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="title-wrap d-flex justify-content-between">
              <div class="title-box">
                <h2 class="title-a">{{__('Featured Category')}}</h2>
              </div>            
            </div>
          </div>
        </div>
        <div id="" class="category-section">
          <div class="row">          
            @foreach ($category as $item)
              <div class="carousel-item-c col-lg-3 col-md-6 col-sm-6">
                <div class="card-box-b card-shadow news-box radius-10">
                  <div class="img-box-b">
                    <img src="{{url('images/upload/'.$item->image)}}" alt="" class="img-b img-fluid">
                  </div>
                  <div class="card-overlay">
                    <div class="card-header-b">                     
                      <div class="card-title-b">
                        <h2 class="title-2">
                          <a href="{{url('events-category/'.$item->id.'/'. preg_replace('/\s+/', '-', $item->name))}}">{{$item->name}}</a>
                        </h2>
                      </div>                     
                    </div>
                  </div>
                </div>
              </div>
            @endforeach    
          </div>               
        </div>
      </div>
    </section> -->

    <section class="section-blog section-t8">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="title-wrap d-flex justify-content-between">
              <div class="title-box">
                <h2 class="title-a">{{__('Our Latest blog')}} </h2>
              </div>            
            </div>
          </div>
        </div>       
        <div id="blog-carousel" class="owl-carousel owl-theme blog-section">
          @foreach ($blog as $item)
            <div class="carousel-item-c">
              <div class="fav-section">  
                @if(Auth::guard('appuser')->check())                                     
                  <button type="button" onclick="addFavorite({{$item->id}},'blog')" class="btn p-0"> <i class="fa fa-heart {{in_array($item->id,array_filter(explode(',',Auth::guard('appuser')->user()->favorite_blog)))==true?'active':''}}"></i></button>
                @else 
                  <button type="button" class="btn p-0"> <a href="{{url('user/login')}}"><i class="fa fa-heart"></i></a></button>
                @endif
              </div>
              <div class="card-box-b card-shadow news-box radius-10">
                <div class="img-box-b">
                  <img src="{{url('images/upload/'.$item->image)}}" alt="" class="img-b img-fluid">
                </div>
                <div class="card-overlay"></div>               
              </div>
              <div class="card-header-b">
                <div class="card-title-b">
                  <h2 class="title-2">
                    <a href="{{url('blog-detail/'.$item->id.'/'.preg_replace('/\s+/', '-', $item->title))}}" title="{{$item->title}}">{{strlen($item->title)>=50? substr($item->title,0,50).'...':$item->title}} </a>
                  </h2>
                </div>
                <div class="card-category-b">
                  <span><i class="fa fa-sitemap"></i>{{$item->category->name}}</span>
                  <span class="date-b"><i class="fa fa-calendar"></i>{{$item->created_at->format('d M.Y')}}</span>
                </div>            
              </div>
            </div> 
          @endforeach
        </div>
      </div>
    </section>
@endsection

resources/views/frontend/payment.blade.php
@extends('frontend.master', ['activePage' => 'profile'])

@section('content')

    <section class="agent-single">
        <div class="profile-top-section" style="background-image: url('https://wallpapercave.com/wp/q1QDvC6.jpg')">
            <div class="profile-overly"></div>
        </div>
        <div class="container">
            <div class="row">
                @if($payment->paid_status == 1)
                    <div class="col-md-12">
                        <div class="alert alert-success">
                            <h4>Payment Successful</h4>
                            <p>Your payment has been successfully completed. <br/>Your Transaction reference number: <b><u>{{$payment->stripe_payment_id}}</u></b></p>
                        </div>
                    </div>
                @else
                    <div class="col-md-12">
                        <div class="alert alert-danger">
                            <h4>Payment Failed/Pending</h4>
                            <p>Your payment has been failed/pending for update, kindly refresh the page after sometime if payment is done successfully or Contact support with your Transaction reference number: <b><u>{{$payment->stripe_payment_id}}</u></b></p>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </section>


@endsection